# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-11 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170510_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_addreaa',
            field=models.EmailField(help_text='your will be needed for communication', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(help_text='Please include your country code.', max_length=16, null=True),
        ),
    ]
