# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-11 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170511_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_addreaa',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(help_text='We communicate via email.', max_length=100, null=True),
        ),
    ]
