# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='sponsor name')),
                ('category', models.CharField(choices=[('Bronze', 'Bronze - $500'), ('Silver', 'Silver - $1000'), ('Gold', 'Gold - $2000'), ('Platinum', 'Platinum - $5000')], max_length=15)),
                ('logo', models.ImageField(max_length=255, upload_to='')),
                ('type', models.CharField(max_length=15, verbose_name='sponsor type')),
            ],
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='subscription',
            name='date_sub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date subscribed'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
