# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170422_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'managed': True},
        ),
    ]
