# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170422_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
