# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='category',
            field=models.CharField(choices=[('Bronze', 'Bronze - $500'), ('Silver', 'Silver - $1000'), ('Gold', 'Gold - $2000'), ('Platinum', 'Platinum - $5000'), ('Other', 'Other')], max_length=15),
        ),
    ]
