# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-20 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_talkschedule_day_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('conference_day', models.CharField(choices=[('1', 'Day 1 - Workshops'), ('2', 'Day 2 - Talks'), ('3', 'Day 3 - Talks'), ('4', 'Day 4 - Sprints')], default='', max_length=1)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('day_session', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='', max_length=10)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
