# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-20 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_day', models.CharField(max_length=30)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='conference_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Day'),
        ),
        migrations.AlterField(
            model_name='talkschedule',
            name='conference_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Day'),
        ),
    ]
