# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-19 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20170721_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.CharField(choices=[('Room 1', 'Room 1'), ('Room 2', 'Room 2')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='talkschedule',
            name='room',
            field=models.CharField(choices=[('Room 1', 'Room 1'), ('Room 2', 'Room 2')], default='', max_length=10),
        ),
    ]
