# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 01:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markitup.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('title', models.CharField(max_length=1024)),
                ('abstract', markitup.fields.MarkupField(help_text='Describe what your talk is about', no_rendered_field=True)),
                ('proposal_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('_abstract_rendered', models.TextField(blank=True, editable=False)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Talk_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Short_Talk'), ('L', 'Long_Talk'), ('T', 'Tutorial')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='talk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talks.Talk_Type'),
        ),
    ]
