# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('A', 'Accepted'), ('W', 'Waiting List'), ('R', 'Rejected')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='talk_type',
            field=models.CharField(choices=[('K', 'Keynote Talk - 45 mins'), ('S', 'Short Talk - 30 mins'), ('L', 'Long Talk - 1 hour'), ('T', 'Tutorial - 2 hours or more')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Talk_Type',
        ),
    ]
