# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_auto_20170422_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='experience_level',
            field=models.CharField(choices=[('B', 'Beginner, no prior knowledge of Python required'), ('A', 'Average, some prior knowledge of Python required '), ('G', 'Good Python programmers level'), ('E', 'Experienced Python programmers level')], default='', max_length=1),
        ),
    ]
