# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_proposal_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='notes',
            field=models.TextField(default=None, help_text='Anything else you would want the organizers to know.Wi-fi requirments, if tutorial, number of people you can manage e.t.cThis will note be published on website'),
        ),
    ]
