# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-31 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_proposal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Anything else you would want the organizers to know.Wi-fi requirments, if tutorial, number of people you can manage e.t.c.This will not be published on website.', null=True),
        ),
    ]
