# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-02 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_auto_20170531_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='author',
            new_name='user',
        ),
    ]
