# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_auto_20170506_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='notes',
            field=models.TextField(default='', help_text='Anything else you would want the organizers to know.Wi-fi requirments, if tutorial, number of people you can manage e.t.cThis will not be published on the website'),
        ),
    ]
