# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0011_auto_20170623_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='recipient_group',
            field=models.CharField(choices=[('S', 'Submitted'), ('A', 'Accepted'), ('W', 'Waiting List'), ('R', 'Rejected')], max_length=50),
        ),
    ]
